import type { Product } from '../types/product'

// Hardcoded products for Phase 4 — swap out once Tavily is wired.
// Images use Unsplash with stable IDs so they don't rotate.
export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'depop:mock-001',
    retailer: 'depop',
    title: 'Y2K Butterfly Mini Skirt',
    description: 'Iconic 2000s butterfly print mini skirt, size S. Pink and lavender on white.',
    price: 28,
    currency: 'USD',
    image_urls: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=400'],
    product_url: 'https://depop.com/products/mock-001',
    sustainability_score: 82,
    score_explanation: 'Secondhand item from a verified seller; significant carbon savings vs. new.',
  },
  {
    id: 'vinted:mock-002',
    retailer: 'vinted',
    title: 'Levi\'s 501 Vintage Straight Jeans',
    description: '90s Levi\'s 501. High waist, straight leg. Light wash. Size 27.',
    price: 45,
    currency: 'USD',
    image_urls: ['https://images.unsplash.com/photo-1542272454315-4c01d7abdf4a?w=400'],
    product_url: 'https://vinted.com/products/mock-002',
    sustainability_score: 78,
    score_explanation: 'Vintage Levi\'s from ethical brand; pre-loved extends garment life.',
  },
  {
    id: 'thredup:mock-003',
    retailer: 'thredup',
    title: 'Dark Academia Plaid Blazer',
    description: 'Oversized black and white plaid blazer. Fully lined. Size M.',
    price: 34,
    currency: 'USD',
    image_urls: ['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400'],
    product_url: 'https://thredup.com/products/mock-003',
    sustainability_score: 71,
    score_explanation: 'ThredUp-verified secondhand; blazer construction means long lifespan.',
  },
  {
    id: 'depop:mock-004',
    retailer: 'depop',
    title: 'Cottagecore Prairie Maxi Dress',
    description: 'Flowy floral maxi in sage green. Puff sleeves, smocked waist. Size S/M.',
    price: 38,
    currency: 'USD',
    image_urls: ['https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400'],
    product_url: 'https://depop.com/products/mock-004',
    sustainability_score: 68,
    score_explanation: 'Pre-owned natural-look fabrication; brand rating not confirmed.',
  },
  {
    id: 'vestiaire:mock-005',
    retailer: 'vestiaire',
    title: 'Coach Patchwork Denim Bag',
    description: 'Vintage Coach patchwork denim shoulder bag. Excellent condition.',
    price: 120,
    currency: 'USD',
    image_urls: ['https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400'],
    product_url: 'https://vestiairecollective.com/products/mock-005',
    sustainability_score: 85,
    score_explanation: 'Luxury re-sale keeps high-quality goods in use; authenticated pre-owned.',
  },
  {
    id: 'ebay:mock-006',
    retailer: 'ebay',
    title: 'Adidas Firebird Track Jacket',
    description: 'Classic Adidas Firebird in royal blue + white. Vintage 2000s. Size L.',
    price: 52,
    currency: 'USD',
    image_urls: ['https://images.unsplash.com/photo-1556306535-0f09a537f0a3?w=400'],
    product_url: 'https://ebay.com/itm/mock-006',
    sustainability_score: 75,
    score_explanation: 'Secondhand sportswear reduces demand for new synthetic production.',
  },
  {
    id: 'whatnot:mock-007',
    retailer: 'whatnot',
    title: 'BCBG Max Azria Slip Dress',
    description: 'Silky bias-cut slip dress in champagne. Size 4. Minimal wear.',
    price: 65,
    currency: 'USD',
    image_urls: ['https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=400'],
    product_url: 'https://whatnot.com/product/mock-007',
    sustainability_score: 62,
    score_explanation: 'Pre-loved designer; brand rated moderate on ethical practices.',
  },
  {
    id: 'depop:mock-008',
    retailer: 'depop',
    title: 'Streetwear Cargo Pants Olive',
    description: 'Wide-leg cargo pants in olive. Six pockets, drawstring hem. Size M.',
    price: 42,
    currency: 'USD',
    image_urls: ['https://images.unsplash.com/photo-1594938298603-c8148c4b4cd5?w=400'],
    product_url: 'https://depop.com/products/mock-008',
    sustainability_score: 73,
    score_explanation: 'Secondhand utility wear; cotton construction supports longevity.',
  },
  {
    id: 'vinted:mock-009',
    retailer: 'vinted',
    title: 'Ralph Lauren Polo Knit Cardigan',
    description: 'Cable-knit cardigan in cream. Ralph Lauren Polo. Size M. Great condition.',
    price: 30,
    currency: 'USD',
    image_urls: ['https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=400'],
    product_url: 'https://vinted.com/products/mock-009',
    sustainability_score: 70,
    score_explanation: 'Natural wool blend; buying pre-loved extends this durable piece.',
  },
  {
    id: 'thredup:mock-010',
    retailer: 'thredup',
    title: 'Free People Boho Crochet Top',
    description: 'Free People crochet halter top. Earthy tan. Size XS/S.',
    price: 22,
    currency: 'USD',
    image_urls: ['https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=400'],
    product_url: 'https://thredup.com/products/mock-010',
    sustainability_score: 67,
    score_explanation: 'Handcraft-style construction; Free People rated moderate on sustainability.',
  },
  {
    id: 'depop:mock-011',
    retailer: 'depop',
    title: 'Vintage 90s Rave Bodysuit',
    description: 'Neon orange and pink holographic rave bodysuit. One size fits most.',
    price: 19,
    currency: 'USD',
    image_urls: ['https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=400'],
    product_url: 'https://depop.com/products/mock-011',
    sustainability_score: 58,
    score_explanation: 'Secondhand extends life but synthetic holographic material is not biodegradable.',
  },
  {
    id: 'vestiaire:mock-012',
    retailer: 'vestiaire',
    title: 'Burberry Nova Check Mini Skirt',
    description: 'Authentic Burberry Nova check wool mini. Size UK 10. Certificate included.',
    price: 220,
    currency: 'USD',
    image_urls: ['https://images.unsplash.com/photo-1583744946564-b52d01a7b321?w=400'],
    product_url: 'https://vestiairecollective.com/products/mock-012',
    sustainability_score: 88,
    score_explanation: 'Authenticated Burberry resale; wool heritage piece saves significant new-production emissions.',
  },
  {
    id: 'ebay:mock-013',
    retailer: 'ebay',
    title: 'Tommy Hilfiger Windbreaker',
    description: 'Classic 90s Tommy Hilfiger color-block windbreaker. Size L. Excellent.',
    price: 60,
    currency: 'USD',
    image_urls: ['https://images.unsplash.com/photo-1591370874773-6702e8f12fd8?w=400'],
    product_url: 'https://ebay.com/itm/mock-013',
    sustainability_score: 74,
    score_explanation: 'Secondhand outerwear with long use ahead; Tommy rated fair on labour.',
  },
  {
    id: 'whatnot:mock-014',
    retailer: 'whatnot',
    title: 'Minimalist COS Linen Trousers',
    description: 'COS wide-leg linen trousers in ecru. Size 36. Barely worn.',
    price: 48,
    currency: 'USD',
    image_urls: ['https://images.unsplash.com/photo-1594938291221-94f18cbb5648?w=400'],
    product_url: 'https://whatnot.com/product/mock-014',
    sustainability_score: 80,
    score_explanation: 'Linen is a low-impact crop; COS parent (H&M Group) has sustainability commitments.',
  },
  {
    id: 'depop:mock-015',
    retailer: 'depop',
    title: 'Y2K Baby Tee Rhinestone Butterfly',
    description: 'White ribbed baby tee with rhinestone butterfly print. Crop fit. Size S.',
    price: 15,
    currency: 'USD',
    image_urls: ['https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=400'],
    product_url: 'https://depop.com/products/mock-015',
    sustainability_score: 76,
    score_explanation: 'Pre-loved Y2K piece; secondhand cotton tee avoids significant water use.',
  },
  {
    id: 'thredup:mock-016',
    retailer: 'thredup',
    title: 'Patagonia Fleece Pullover',
    description: 'Patagonia Better Sweater fleece in navy. Size M. Certified recycled polyester.',
    price: 55,
    currency: 'USD',
    image_urls: ['https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400'],
    product_url: 'https://thredup.com/products/mock-016',
    sustainability_score: 93,
    score_explanation: 'Patagonia is a top-rated ethical brand; pre-loved recycled fleece is best-in-class.',
  },
  {
    id: 'vinted:mock-017',
    retailer: 'vinted',
    title: 'Dark Academia Corduroy Trousers',
    description: 'Wide-leg brown corduroy trousers. High rise. Size 28.',
    price: 35,
    currency: 'USD',
    image_urls: ['https://images.unsplash.com/photo-1560343090-f0409e92791a?w=400'],
    product_url: 'https://vinted.com/products/mock-017',
    sustainability_score: 69,
    score_explanation: 'Corduroy is a durable weave; buying secondhand avoids new production entirely.',
  },
  {
    id: 'ebay:mock-018',
    retailer: 'ebay',
    title: 'Vintage Silk Slip Skirt',
    description: 'Bias-cut silk midi slip skirt in dusty rose. Size 6. Early 2000s.',
    price: 40,
    currency: 'USD',
    image_urls: ['https://images.unsplash.com/photo-1557804506-669a67965ba0?w=400'],
    product_url: 'https://ebay.com/itm/mock-018',
    sustainability_score: 72,
    score_explanation: 'Natural silk fibre; buying vintage avoids new dye-and-weave emissions.',
  },
  {
    id: 'depop:mock-019',
    retailer: 'depop',
    title: 'Streetwear Oversized Hoodie',
    description: 'Heavyweight washed black hoodie. Dropped shoulders. Size L (fits oversized on M).',
    price: 32,
    currency: 'USD',
    image_urls: ['https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=400'],
    product_url: 'https://depop.com/products/mock-019',
    sustainability_score: 64,
    score_explanation: 'Pre-loved cotton fleece; brand origin unclear, score estimated conservatively.',
  },
  {
    id: 'vestiaire:mock-020',
    retailer: 'vestiaire',
    title: 'Chloé Paddington Bag',
    description: 'Iconic Chloé Paddington bag in tan leather. Excellent condition with dust bag.',
    price: 480,
    currency: 'USD',
    image_urls: ['https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=400'],
    product_url: 'https://vestiairecollective.com/products/mock-020',
    sustainability_score: 86,
    score_explanation: 'Authenticated luxury resale prevents landfill and avoids new production of a high-impact item.',
  },
  {
    id: 'whatnot:mock-021',
    retailer: 'whatnot',
    title: 'Vintage Levi\'s Trucker Jacket',
    description: 'Classic Levi\'s type III trucker in medium wash. Size S. 1990s.',
    price: 72,
    currency: 'USD',
    image_urls: ['https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=400'],
    product_url: 'https://whatnot.com/product/mock-021',
    sustainability_score: 84,
    score_explanation: 'Levi\'s is a relatively ethical denim brand; vintage trucker is a long-life classic.',
  },
  {
    id: 'thredup:mock-022',
    retailer: 'thredup',
    title: 'Reformation Sundress Floral',
    description: 'Reformation floral wrap midi dress. Deadstock fabric. Size 4.',
    price: 68,
    currency: 'USD',
    image_urls: ['https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=400'],
    product_url: 'https://thredup.com/products/mock-022',
    sustainability_score: 91,
    score_explanation: 'Reformation uses sustainable and deadstock materials; pre-loved amplifies this further.',
  },
]
