ALTER TABLE products
  ADD COLUMN IF NOT EXISTS brand TEXT,
  ADD COLUMN IF NOT EXISTS source_search_url TEXT,
  ADD COLUMN IF NOT EXISTS source_domain TEXT,
  ADD COLUMN IF NOT EXISTS scrape_status TEXT NOT NULL DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS scrape_version INTEGER NOT NULL DEFAULT 2,
  ADD COLUMN IF NOT EXISTS scraped_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS score_version INTEGER NOT NULL DEFAULT 0;
